-- Seed data generated from the original hardcoded squad.html array.
-- Run in Supabase SQL Editor AFTER schema.sql, once (re-running would duplicate rows).

insert into players (name, role, emoji, captain, photo_path, sort_order) values
  ('Awanish', 'All-Rounder', '🏏⚾︎', true, 'awanish.png', 1),
  ('Sameer', 'Batsman', '🏏', false, 'sameer.png', 2),
  ('Ananta', 'Batsman', '🏏', false, 'ananta.png', 3),
  ('Krishna', 'Batsman', '🏏', false, 'krishna.png', 4),
  ('Ashim', 'All-Rounder', '🏏⚾︎', false, 'ashim.png', 5),
  ('Pradeep', 'All-Rounder', '🏏⚾︎', false, 'pradeep.png', 6),
  ('Suraj', 'All-Rounder', '🏏🧤⚾︎', false, 'suraj.png', 7),
  ('Mubesh', 'Batsman', '🏏', false, 'mubesh.png', 8),
  ('Subash', 'Bowler', '⚾︎', false, 'subash.png', 9),
  ('Manoj', 'Bowler', '⚾︎', false, 'manoj.png', 10),
  ('Sanjay', 'Batsman', '🏏', false, 'sanjay.png', 11),
  ('Kshitiz', 'All-Rounder', '🏏⚾︎', false, 'kshitiz.png', 12),
  ('Robin', 'Bowler', '⚾︎', false, 'roben.png', 13),
  ('Niwesh', 'Batsman', '🏏', false, 'niwesh.png', 14),
  ('Lokesh', 'Batsman', '🏏', false, 'lokesh.png', 15),
  ('Bikash', 'Batsman', '🏏', false, 'bikash.png', 16),
  ('Agin', 'All-Rounder', '🏏⚾︎', false, 'agin.png', 17),
  ('Nitesh', 'All-Rounder', '🏏⚾︎', false, 'nitesh.png', 18),
  ('Bikram', 'Batsman', '🏏', false, 'bikram.png', 19),
  ('Kushal', 'Batsman', '🏏', false, 'kushal.png', 20),
  ('Sushant', 'Bowler', '⚾︎', false, 'sushant.png', 21),
  ('Pawan', 'All-Rounder', '🏏⚾︎', false, 'pawan.png', 22),
  ('Shushovan', 'All-Rounder', '🏏⚾︎', false, 'sakya.png', 23),
  ('Cheeran', 'All-Rounder', '🏏⚾︎', false, 'cheeran.png', 24),
  ('Manish', 'Batsman', '🏏', false, 'manish.png', 25),
  ('Janak', 'All-Rounder', '🏏⚾︎', false, 'janak.png', 26),
  ('Biplab', 'All-Rounder', '🏏⚾︎', false, 'biplap.png', 27),
  ('Sudip', 'Batsman', '🏏', false, 'sudip.png', 28),
  ('Nabin', 'Batsman', '🏏', false, 'nabin.png', 29),
  ('Dipesh', 'Batsman', '🏏', false, 'dipesh.png', 30),
  ('Sujan', 'Batsman', '🏏', false, 'sujan.png', 31),
  ('Niroj', 'Batsman', '🏏', false, 'niroj.png', 32),
  ('Razu', 'Batsman', '🏏', false, 'razu.png', 33),
  ('Dipendra', 'Bowler', '⚾︎', false, 'dipendra.png', 34);
